apiVersion: v1
kind: Pod
metadata:
  name: hello-crtl
  annotations:
    k8s.v1.cni.cncf.io/networks: vmgmtpod1@eth1
spec:
  containers: 
  - name: hello-crtl
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
