apiVersion: v1
kind: Pod
metadata:
  name: ned-domain-2
  annotations:
    k8s.v1.cni.cncf.io/networks: > 
        vdatahost1@data1, vdatahost2@data2, vdatahost3@data3, vdatahost4@data4, vdatahost5@data5, vdatahost6@data6, vdatahost7@data7, vdatahost8@data8, vdatahost9@data9, vdatahost10@data10, 
        vctrlhost1@ctrl1, vctrlhost2@ctrl2, vctrlhost3@ctrl3, vctrlhost4@ctrl4, vctrlhost5@ctrl5, vctrlhost6@ctrl6, vctrlhost7@ctrl7, vctrlhost8@ctrl8, vctrlhost9@ctrl9, vctrlhost10@ctrl10, 
        vxlan3@vxlan-ctrl, vxlan2@vxlan-domain1
spec:
  containers: 
  - name: ned-domain-2
    image: lewisfelix24/ovs-pod-ml2s:amd64
    command: ["/bin/sh", "-c"]
    args: ["ovsdb-server --remote=punix:/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile=/var/run/openvswitch/ovsdb-server.pid --detach && ovs-vsctl --db=unix:/var/run/openvswitch/db.sock --no-wait init && ovs-vswitchd --pidfile=/var/run/openvswitch/ovs-vswitchd.pid --detach && /bin/sleep 3650d"]
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
