apiVersion: v1
kind: Pod
metadata:
  name: hello-sandbox
  labels:
    app: hello-sandbox
  annotations:
    k8s.v1.cni.cncf.io/networks: vdatapod4@data, vmgmtpod4@mgmt
spec:
  containers: 
  - name: hello-sandbox
    image: nginx
    command: ["/bin/sh", "-c"]
    args: ["apt update && apt install -y iproute2 iputils-ping && ip link set data up && ip link set mgmt up && /bin/sleep 3650d"] 
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
